# Generated by Django 4.0.4 on 2022-05-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('XS', models.IntegerField()),
                ('S', models.IntegerField()),
                ('L', models.IntegerField()),
                ('M', models.IntegerField()),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_commission_percent', models.FloatField()),
                ('total_transactions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('sales_sum', models.IntegerField(default=0)),
                ('image', models.ImageField(default='img/default-avatar.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('bank_card_no', models.CharField(blank=True, max_length=20)),
                ('expiration_date', models.CharField(blank=True, max_length=15)),
                ('CVV', models.CharField(blank=True, max_length=3)),
                ('total_purchases', models.IntegerField(default=0)),
                ('discount_id', models.CharField(blank=True, max_length=3)),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.bank_card')),
            ],
        ),
        migrations.CreateModel(
            name='Customers_Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('total_sum', models.IntegerField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.consultants')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
                ('starter_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Other_offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(default='zhai.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.articles')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.customers_purchase')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.product_types'),
        ),
    ]
