# Generated by Django 4.0.4 on 2022-05-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
