# Generated by Django 4.0.4 on 2022-05-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_purchases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
