# Generated by Django 4.0.4 on 2022-05-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
