# Generated by Django 4.0.4 on 2022-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connect', '0004_delete_doctor_delete_product_delete_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_commission_percent', models.FloatField()),
                ('total_transactions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('sales_sum', models.IntegerField()),
                ('image', models.ImageField(default='https://via.placeholder.com/300x300', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
                ('starter_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Other_offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(default='https://via.placeholder.com/300x300', upload_to='')),
            ],
        ),
    ]
